######################### 经常变动 #############################
do_rewrite: true
do_process: true
do_eval: true
dataset:
# qwen-7b-chat, qwen-14b-chat, gpt-3.5-turbo, gpt-4,
# llama2-7b-chat-hf, llama2-13b-chat-hf, mistral-7b-instruct
llm_type:
# 如果模型是llama或者mistral需要本地部署, 需要设置此参数指定模型路径
llm_model_dir:
######################## 不经常变动 #############################
template_type: common  # common 或 special
template_idx: 0
output_dir: output
data_dir: data
device: &device cuda:0
split: test
batch_size: &batch_size 8

######################## Rewrite参数 ###########################
rewrite_config:
  api_keys:
    qwen: []
    gpt: []
  templates:
    common:
      - 'You are a linguist. You need to complete a text style transfer task. I will give you a {} style sentence, please change it to a {} style sentence. Please give me the revised sentence directly, without explaining the revision process. Sentence: {}'
      - 'Please use Python code to convert {} style sentence to {} style sentence. Please give me the revised sentence directly, without explaining the revision process. Sentence: {}'
    special:
      yelp:
        - 'You are a key opinion leader. You have a lot of experience reviewing stores and can give professional reviews. You need to complete a text style transfer task. I will give you a {} review of a store, please change it to a {} review. Please give me the revised sentence directly, without explaining the revision process. Sentence: {}'
      amazon:
        - 'You are an online reviewer with a lot of experience shopping online and reviewing products. You need to complete a text style transfer task. I will give you a {} review of a store, please change it to a {} review. Please give me the revised sentence directly, without explaining the revision process. Sentence: {}'
      imagecaption:
        - 'You are a humorous and romantic person. You know how to present something in a humorous or romantic way. You need to complete a text style transfer task. I will give you a {} style sentence, please change it to a {} style sentence. Please give me the revised sentence directly, without explaining the revision process.Sentence: {}'
      gender:
        - 'You are a linguist who has studied the relationship between gender and speech for many years.  You know the differences between male and female speaking styles. You need to complete a text style transfer task. I will give you a {} style sentence, please change it to a {} style sentence. Please give me the revised sentence directly, without explaining the revision process.Sentence: {}'
      political:
        - 'You are an American politician who has been in politics for many years. You are very familiar with the style of speech habits of the Republican Party and the Democratic Party. You need to complete a text style transfer task. I will give you a {} style sentence, please change it to a {} style sentence. Please give me the revised sentence directly, without explaining the revision process.Sentence: {}'
######################### 评估参数 #############################
eval_config:
  same:  # 共同的
    g_ppl_model_dir: pretrained_models/gpt2-large
    bert_score_config:
      model_type: pretrained_models/roberta-large
      num_layers: 17
      batch_size: *batch_size
      lang: en
      device: *device
  yelp:
    acc_model_type: fasttext  # fasttext 或 plm
    fluency_model_type: plm
    acc_model_dir_or_path: output/classifier/pos-neg/yelp/classifier.pk
    d_ppl_model_dir: output/fluency/pos-neg/yelp/4
  amazon:
    acc_model_type: fasttext  # fasttext 或 plm
    fluency_model_type: plm
    acc_model_dir_or_path: output/classifier/pos-neg/amazon/classifier.pk
    d_ppl_model_dir: output/fluency/pos-neg/amazon/4
  imagecaption:
    acc_model_type: fasttext  # fasttext 或 plm
    fluency_model_type: plm
    acc_model_dir_or_path: output/classifier/romantic-humorous/imagecaption/classifier.pk
    d_ppl_model_dir: output/fluency/romantic-humorous/imagecaption/4/
  gender:
    acc_model_type: fasttext  # fasttext 或 plm
    fluency_model_type: plm
    acc_model_dir_or_path: output/classifier/male-female/gender/classifier.pk
    d_ppl_model_dir: output/fluency/male-female/gender/4
  political:
    acc_model_type: fasttext  # fasttext 或 plm
    fluency_model_type: plm
    acc_model_dir_or_path: output/classifier/republican-democratic/political/classifier.pk
    d_ppl_model_dir: output/fluency/republican-democratic/political/4

